// <auto-generated />
using System;
using CarService.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace avtoservis.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260517154708_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("CarService.API.Models.Car", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ClientId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LicensePlate")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.ToTable("Cars");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Brand = "Toyota",
                            ClientId = 1,
                            LicensePlate = "А001АА77",
                            Model = "Camry"
                        },
                        new
                        {
                            Id = 2,
                            Brand = "Honda",
                            ClientId = 1,
                            LicensePlate = "Б002ББ77",
                            Model = "Civic"
                        },
                        new
                        {
                            Id = 3,
                            Brand = "BMW",
                            ClientId = 2,
                            LicensePlate = "В003ВВ77",
                            Model = "X5"
                        },
                        new
                        {
                            Id = 4,
                            Brand = "Mercedes",
                            ClientId = 3,
                            LicensePlate = "Г004ГГ77",
                            Model = "E-Class"
                        },
                        new
                        {
                            Id = 5,
                            Brand = "Lada",
                            ClientId = 4,
                            LicensePlate = "Д005ДД77",
                            Model = "Vesta"
                        },
                        new
                        {
                            Id = 6,
                            Brand = "Kia",
                            ClientId = 5,
                            LicensePlate = "Е006ЕЕ77",
                            Model = "Rio"
                        },
                        new
                        {
                            Id = 7,
                            Brand = "Hyundai",
                            ClientId = 6,
                            LicensePlate = "Ж007ЖЖ77",
                            Model = "Solaris"
                        },
                        new
                        {
                            Id = 8,
                            Brand = "Ford",
                            ClientId = 7,
                            LicensePlate = "З008ЗЗ77",
                            Model = "Focus"
                        },
                        new
                        {
                            Id = 9,
                            Brand = "Volkswagen",
                            ClientId = 8,
                            LicensePlate = "И009ИИ77",
                            Model = "Polo"
                        },
                        new
                        {
                            Id = 10,
                            Brand = "Nissan",
                            ClientId = 9,
                            LicensePlate = "К010КК77",
                            Model = "Qashqai"
                        },
                        new
                        {
                            Id = 11,
                            Brand = "Renault",
                            ClientId = 10,
                            LicensePlate = "Л011ЛЛ77",
                            Model = "Logan"
                        },
                        new
                        {
                            Id = 12,
                            Brand = "Skoda",
                            ClientId = 11,
                            LicensePlate = "М012ММ77",
                            Model = "Octavia"
                        },
                        new
                        {
                            Id = 13,
                            Brand = "Mazda",
                            ClientId = 12,
                            LicensePlate = "Н013НН77",
                            Model = "CX-5"
                        },
                        new
                        {
                            Id = 14,
                            Brand = "Subaru",
                            ClientId = 2,
                            LicensePlate = "О014ОО77",
                            Model = "Outback"
                        },
                        new
                        {
                            Id = 15,
                            Brand = "Audi",
                            ClientId = 3,
                            LicensePlate = "П015ПП77",
                            Model = "A4"
                        },
                        new
                        {
                            Id = 16,
                            Brand = "Mitsubishi",
                            ClientId = 5,
                            LicensePlate = "Р016РР77",
                            Model = "Outlander"
                        });
                });

            modelBuilder.Entity("CarService.API.Models.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Clients");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Алексей Петров",
                            Phone = "+7-900-111-0001"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Мария Иванова",
                            Phone = "+7-900-111-0002"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Дмитрий Смирнов",
                            Phone = "+7-900-111-0003"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Елена Кузнецова",
                            Phone = "+7-900-111-0004"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Сергей Попов",
                            Phone = "+7-900-111-0005"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Ольга Новикова",
                            Phone = "+7-900-111-0006"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Андрей Морозов",
                            Phone = "+7-900-111-0007"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Татьяна Волкова",
                            Phone = "+7-900-111-0008"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Николай Лебедев",
                            Phone = "+7-900-111-0009"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Анна Соколова",
                            Phone = "+7-900-111-0010"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Павел Козлов",
                            Phone = "+7-900-111-0011"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Виктория Орлова",
                            Phone = "+7-900-111-0012"
                        });
                });

            modelBuilder.Entity("CarService.API.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CarId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClientId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CarId");

                    b.HasIndex("ClientId");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CarId = 1,
                            ClientId = 1,
                            Status = 2
                        },
                        new
                        {
                            Id = 2,
                            CarId = 2,
                            ClientId = 1,
                            Status = 2
                        },
                        new
                        {
                            Id = 3,
                            CarId = 3,
                            ClientId = 2,
                            Status = 2
                        },
                        new
                        {
                            Id = 4,
                            CarId = 4,
                            ClientId = 3,
                            Status = 1
                        },
                        new
                        {
                            Id = 5,
                            CarId = 5,
                            ClientId = 4,
                            Status = 1
                        },
                        new
                        {
                            Id = 6,
                            CarId = 6,
                            ClientId = 5,
                            Status = 2
                        },
                        new
                        {
                            Id = 7,
                            CarId = 7,
                            ClientId = 6,
                            Status = 2
                        },
                        new
                        {
                            Id = 8,
                            CarId = 8,
                            ClientId = 7,
                            Status = 0
                        },
                        new
                        {
                            Id = 9,
                            CarId = 9,
                            ClientId = 8,
                            Status = 1
                        },
                        new
                        {
                            Id = 10,
                            CarId = 10,
                            ClientId = 9,
                            Status = 2
                        },
                        new
                        {
                            Id = 11,
                            CarId = 11,
                            ClientId = 10,
                            Status = 2
                        },
                        new
                        {
                            Id = 12,
                            CarId = 12,
                            ClientId = 11,
                            Status = 0
                        },
                        new
                        {
                            Id = 13,
                            CarId = 13,
                            ClientId = 12,
                            Status = 2
                        },
                        new
                        {
                            Id = 14,
                            CarId = 14,
                            ClientId = 2,
                            Status = 2
                        },
                        new
                        {
                            Id = 15,
                            CarId = 15,
                            ClientId = 3,
                            Status = 1
                        },
                        new
                        {
                            Id = 16,
                            CarId = 16,
                            ClientId = 5,
                            Status = 2
                        },
                        new
                        {
                            Id = 17,
                            CarId = 1,
                            ClientId = 1,
                            Status = 0
                        },
                        new
                        {
                            Id = 18,
                            CarId = 5,
                            ClientId = 4,
                            Status = 2
                        },
                        new
                        {
                            Id = 19,
                            CarId = 7,
                            ClientId = 6,
                            Status = 1
                        },
                        new
                        {
                            Id = 20,
                            CarId = 10,
                            ClientId = 9,
                            Status = 2
                        },
                        new
                        {
                            Id = 21,
                            CarId = 11,
                            ClientId = 10,
                            Status = 2
                        },
                        new
                        {
                            Id = 22,
                            CarId = 13,
                            ClientId = 12,
                            Status = 0
                        });
                });

            modelBuilder.Entity("CarService.API.Models.OrderPart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("OrderId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PartId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("PriceAtOrder")
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("PartId");

                    b.ToTable("OrderParts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            OrderId = 1,
                            PartId = 1,
                            PriceAtOrder = 2800m,
                            Quantity = 1
                        },
                        new
                        {
                            Id = 2,
                            OrderId = 1,
                            PartId = 2,
                            PriceAtOrder = 350m,
                            Quantity = 1
                        },
                        new
                        {
                            Id = 3,
                            OrderId = 2,
                            PartId = 3,
                            PriceAtOrder = 500m,
                            Quantity = 1
                        },
                        new
                        {
                            Id = 4,
                            OrderId = 3,
                            PartId = 4,
                            PriceAtOrder = 1800m,
                            Quantity = 1
                        },
                        new
                        {
                            Id = 5,
                            OrderId = 5,
                            PartId = 1,
                            PriceAtOrder = 2800m,
                            Quantity = 1
                        },
                        new
                        {
                            Id = 6,
                            OrderId = 7,
                            PartId = 8,
                            PriceAtOrder = 2500m,
                            Quantity = 1
                        },
                        new
                        {
                            Id = 7,
                            OrderId = 10,
                            PartId = 1,
                            PriceAtOrder = 2800m,
                            Quantity = 1
                        },
                        new
                        {
                            Id = 8,
                            OrderId = 10,
                            PartId = 2,
                            PriceAtOrder = 350m,
                            Quantity = 1
                        },
                        new
                        {
                            Id = 9,
                            OrderId = 13,
                            PartId = 6,
                            PriceAtOrder = 5500m,
                            Quantity = 1
                        });
                });

            modelBuilder.Entity("CarService.API.Models.OrderService", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("OrderId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ServiceId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ServiceId");

                    b.ToTable("OrderServices");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            OrderId = 1,
                            ServiceId = 1
                        },
                        new
                        {
                            Id = 2,
                            OrderId = 1,
                            ServiceId = 2
                        },
                        new
                        {
                            Id = 3,
                            OrderId = 2,
                            ServiceId = 3
                        },
                        new
                        {
                            Id = 4,
                            OrderId = 3,
                            ServiceId = 4
                        },
                        new
                        {
                            Id = 5,
                            OrderId = 4,
                            ServiceId = 8
                        },
                        new
                        {
                            Id = 6,
                            OrderId = 5,
                            ServiceId = 1
                        },
                        new
                        {
                            Id = 7,
                            OrderId = 6,
                            ServiceId = 5
                        },
                        new
                        {
                            Id = 8,
                            OrderId = 6,
                            ServiceId = 6
                        },
                        new
                        {
                            Id = 9,
                            OrderId = 7,
                            ServiceId = 9
                        },
                        new
                        {
                            Id = 10,
                            OrderId = 10,
                            ServiceId = 1
                        },
                        new
                        {
                            Id = 11,
                            OrderId = 10,
                            ServiceId = 2
                        },
                        new
                        {
                            Id = 12,
                            OrderId = 13,
                            ServiceId = 7
                        });
                });

            modelBuilder.Entity("CarService.API.Models.Part", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ArticleNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("CompatibleBrands")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Parts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ArticleNumber = "OIL-5W30-4",
                            Category = "Масла",
                            Name = "Масло моторное 5W-30 4л",
                            Price = 2800m,
                            Quantity = 50
                        },
                        new
                        {
                            Id = 2,
                            ArticleNumber = "FLT-OIL-TOY",
                            Category = "Фильтры",
                            Name = "Фильтр масляный Toyota",
                            Price = 350m,
                            Quantity = 30
                        },
                        new
                        {
                            Id = 3,
                            ArticleNumber = "FLT-AIR-001",
                            Category = "Фильтры",
                            Name = "Фильтр воздушный",
                            Price = 500m,
                            Quantity = 25
                        },
                        new
                        {
                            Id = 4,
                            ArticleNumber = "BRK-PAD-F01",
                            Category = "Тормоза",
                            Name = "Тормозные колодки перед",
                            Price = 1800m,
                            Quantity = 20
                        },
                        new
                        {
                            Id = 5,
                            ArticleNumber = "BRK-PAD-R01",
                            Category = "Тормоза",
                            Name = "Тормозные колодки зад",
                            Price = 1500m,
                            Quantity = 20
                        },
                        new
                        {
                            Id = 6,
                            ArticleNumber = "BAT-60AH-001",
                            Category = "Электрика",
                            Name = "Аккумулятор 60Ah",
                            Price = 5500m,
                            Quantity = 10
                        },
                        new
                        {
                            Id = 7,
                            ArticleNumber = "SPK-PLG-004",
                            Category = "Электрика",
                            Name = "Свечи зажигания (к-т 4)",
                            Price = 800m,
                            Quantity = 40
                        },
                        new
                        {
                            Id = 8,
                            ArticleNumber = "TIM-BELT-001",
                            Category = "Двигатель",
                            Name = "Ремень ГРМ",
                            Price = 2500m,
                            Quantity = 15
                        },
                        new
                        {
                            Id = 9,
                            ArticleNumber = "COOL-FL-001",
                            Category = "Жидкости",
                            Name = "Охлаждающая жидкость 1л",
                            Price = 250m,
                            Quantity = 60
                        },
                        new
                        {
                            Id = 10,
                            ArticleNumber = "FLT-FUEL-01",
                            Category = "Фильтры",
                            Name = "Фильтр топливный",
                            Price = 600m,
                            Quantity = 25
                        },
                        new
                        {
                            Id = 11,
                            ArticleNumber = "OIL-TRANS-01",
                            Category = "Масла",
                            Name = "Масло трансмиссионное",
                            Price = 1200m,
                            Quantity = 30
                        },
                        new
                        {
                            Id = 12,
                            ArticleNumber = "SHCK-F-001",
                            Category = "Подвеска",
                            Name = "Амортизатор передний",
                            Price = 3500m,
                            Quantity = 8
                        });
                });

            modelBuilder.Entity("CarService.API.Models.Service", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Services");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Замена масла",
                            Price = 1500m
                        },
                        new
                        {
                            Id = 2,
                            Name = "Замена фильтра",
                            Price = 800m
                        },
                        new
                        {
                            Id = 3,
                            Name = "Диагностика двигателя",
                            Price = 2000m
                        },
                        new
                        {
                            Id = 4,
                            Name = "Замена тормозных колодок",
                            Price = 2500m
                        },
                        new
                        {
                            Id = 5,
                            Name = "Шиномонтаж (1 колесо)",
                            Price = 400m
                        },
                        new
                        {
                            Id = 6,
                            Name = "Балансировка колес",
                            Price = 1200m
                        },
                        new
                        {
                            Id = 7,
                            Name = "Замена аккумулятора",
                            Price = 500m
                        },
                        new
                        {
                            Id = 8,
                            Name = "Компьютерная диагностика",
                            Price = 1800m
                        },
                        new
                        {
                            Id = 9,
                            Name = "Замена ремня ГРМ",
                            Price = 5000m
                        },
                        new
                        {
                            Id = 10,
                            Name = "Мойка двигателя",
                            Price = 3000m
                        });
                });

            modelBuilder.Entity("CarService.API.Models.UserFavorite", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClientId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("ServiceId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("ServiceId");

                    b.ToTable("UserFavorites");
                });

            modelBuilder.Entity("CarService.API.Models.Car", b =>
                {
                    b.HasOne("CarService.API.Models.Client", "Client")
                        .WithMany("Cars")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("CarService.API.Models.Order", b =>
                {
                    b.HasOne("CarService.API.Models.Car", "Car")
                        .WithMany()
                        .HasForeignKey("CarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CarService.API.Models.Client", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Car");

                    b.Navigation("Client");
                });

            modelBuilder.Entity("CarService.API.Models.OrderPart", b =>
                {
                    b.HasOne("CarService.API.Models.Order", "Order")
                        .WithMany()
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CarService.API.Models.Part", "Part")
                        .WithMany("OrderParts")
                        .HasForeignKey("PartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Part");
                });

            modelBuilder.Entity("CarService.API.Models.OrderService", b =>
                {
                    b.HasOne("CarService.API.Models.Order", "Order")
                        .WithMany()
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CarService.API.Models.Service", "Service")
                        .WithMany()
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("CarService.API.Models.UserFavorite", b =>
                {
                    b.HasOne("CarService.API.Models.Client", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CarService.API.Models.Service", "Service")
                        .WithMany()
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("CarService.API.Models.Client", b =>
                {
                    b.Navigation("Cars");
                });

            modelBuilder.Entity("CarService.API.Models.Part", b =>
                {
                    b.Navigation("OrderParts");
                });
#pragma warning restore 612, 618
        }
    }
}
